# Python for Data Analytics

 - Numpy 
 - Pandas 
 - Matplotlib /Seaborn
 - Power Bi
 - Statistics
 - Predictive Analytics (ML )

# Numpy

 - Numerical Python: 
                    - its an array written in C
 
                    - Fast 
                     
                    -  Vectorised Operation    

### Array Creation
       - python list
       - array()
       - arange()
       

In [37]:
# !pip install numpy

In [38]:
import numpy as np

In [39]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [40]:
type(arr)

numpy.ndarray

In [41]:
# array size
arr.size

10

In [42]:
# array shape
arr.shape

(10,)

In [43]:
arr.ndim

1

In [44]:
arr[4]

5

In [45]:
arr[3:7]

array([4, 5, 6, 7])

In [46]:
arr[9:3:-1]

array([10,  9,  8,  7,  6,  5])

# 2D-aRRAY

In [47]:
arr2d = np.array([
                   [1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [11,22,33,44],
                   [11,22,33,44]
                 ])

In [48]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [11, 22, 33, 44],
       [11, 22, 33, 44]])

In [49]:
arr2d.size

20

In [50]:
arr2d.shape

(5, 4)

In [51]:
arr2d.ndim

2

In [52]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [11, 22, 33, 44],
       [11, 22, 33, 44]])

In [53]:
arr2d[1][2]

7

In [54]:
arr2d[1][2]

7

In [55]:
arr2d[1, 2]

7

In [56]:
arr2d[2,2]

11

# Indexing and Slicing

In [57]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [11, 22, 33, 44],
       [11, 22, 33, 44]])

In [58]:
arr2d = np.arange(64).reshape(8,8)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [59]:
# indexing
arr2d[ 1:9,3:6]

array([[11, 12, 13],
       [19, 20, 21],
       [27, 28, 29],
       [35, 36, 37],
       [43, 44, 45],
       [51, 52, 53],
       [59, 60, 61]])

In [60]:
arr2d[2][0]

16

In [61]:
arr2d[3,3]

27

In [63]:
#[r,c]>>> [startrow:endrow   , startcol:endcol]
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [64]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [65]:
arr2d[1:3,1:3]

array([[ 9, 10],
       [17, 18]])

In [66]:
arr2d[2:3,1:3]

array([[17, 18]])

In [67]:
arr2d[:,3:]

array([[ 3,  4,  5,  6,  7],
       [11, 12, 13, 14, 15],
       [19, 20, 21, 22, 23],
       [27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [59, 60, 61, 62, 63]])

In [68]:
arr2d[3:6,2:6]

array([[26, 27, 28, 29],
       [34, 35, 36, 37],
       [42, 43, 44, 45]])

In [69]:
arr2d[1:,4:6]

array([[12, 13],
       [20, 21],
       [28, 29],
       [36, 37],
       [44, 45],
       [52, 53],
       [60, 61]])

In [70]:
arr2d[:,1:7]

array([[ 1,  2,  3,  4,  5,  6],
       [ 9, 10, 11, 12, 13, 14],
       [17, 18, 19, 20, 21, 22],
       [25, 26, 27, 28, 29, 30],
       [33, 34, 35, 36, 37, 38],
       [41, 42, 43, 44, 45, 46],
       [49, 50, 51, 52, 53, 54],
       [57, 58, 59, 60, 61, 62]])

In [71]:
arr2d[4:5,3:5]

array([[35, 36]])

In [72]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [73]:
arr2d[2][6] = 2200

In [74]:
arr2d

array([[   0,    1,    2,    3,    4,    5,    6,    7],
       [   8,    9,   10,   11,   12,   13,   14,   15],
       [  16,   17,   18,   19,   20,   21, 2200,   23],
       [  24,   25,   26,   27,   28,   29,   30,   31],
       [  32,   33,   34,   35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44,   45,   46,   47],
       [  48,   49,   50,   51,   52,   53,   54,   55],
       [  56,   57,   58,   59,   60,   61,   62,   63]])

In [75]:
a=arr2d[2,4]

In [76]:
type(a)

numpy.int32

# array 3d

In [77]:
import numpy as np

In [78]:
arr3d = np.arange(24).reshape(2,4,3) # (depth, row, col)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [79]:
arr3d.ndim

3

In [80]:
arr3d[1,1,1]

16

In [81]:
arr3d[1,2,2]

20

# Vectorized Operation:

In [82]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
lst=[]
for a in arr:
    lst.append(a*10)

In [84]:
lst

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [85]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
arr*10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [88]:
arr2d

array([[   0,    1,    2,    3,    4,    5,    6,    7],
       [   8,    9,   10,   11,   12,   13,   14,   15],
       [  16,   17,   18,   19,   20,   21, 2200,   23],
       [  24,   25,   26,   27,   28,   29,   30,   31],
       [  32,   33,   34,   35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44,   45,   46,   47],
       [  48,   49,   50,   51,   52,   53,   54,   55],
       [  56,   57,   58,   59,   60,   61,   62,   63]])

In [89]:
arr2d/10

array([[0.0e+00, 1.0e-01, 2.0e-01, 3.0e-01, 4.0e-01, 5.0e-01, 6.0e-01,
        7.0e-01],
       [8.0e-01, 9.0e-01, 1.0e+00, 1.1e+00, 1.2e+00, 1.3e+00, 1.4e+00,
        1.5e+00],
       [1.6e+00, 1.7e+00, 1.8e+00, 1.9e+00, 2.0e+00, 2.1e+00, 2.2e+02,
        2.3e+00],
       [2.4e+00, 2.5e+00, 2.6e+00, 2.7e+00, 2.8e+00, 2.9e+00, 3.0e+00,
        3.1e+00],
       [3.2e+00, 3.3e+00, 3.4e+00, 3.5e+00, 3.6e+00, 3.7e+00, 3.8e+00,
        3.9e+00],
       [4.0e+00, 4.1e+00, 4.2e+00, 4.3e+00, 4.4e+00, 4.5e+00, 4.6e+00,
        4.7e+00],
       [4.8e+00, 4.9e+00, 5.0e+00, 5.1e+00, 5.2e+00, 5.3e+00, 5.4e+00,
        5.5e+00],
       [5.6e+00, 5.7e+00, 5.8e+00, 5.9e+00, 6.0e+00, 6.1e+00, 6.2e+00,
        6.3e+00]])

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])