# Transforming Data

### Mapping

In [2]:
import pandas as pd

# create two Series objects to demonstrate mapping
x = pd.Series({"one": 1, "two": 2, "three": 3})
y = pd.Series({1: "a", 2: "b", 3: "c"})
x

one      1
two      2
three    3
dtype: int64

In [3]:
y

1    a
2    b
3    c
dtype: object

In [4]:
# map values in x to values in y
x.map(y)

one      a
two      b
three    c
dtype: object

In [6]:
s = pd.Series(['cat', 'cow', 'dog'])
print(s)

0    cat
1    cow
2    dog
dtype: object


In [7]:
print("Mapping: ")
s.map({'cat': 'kitten', 'cow': 'calf'})

Mapping: 


0    kitten
1      calf
2       NaN
dtype: object

In [9]:
data = pd.DataFrame({'Country':['Pakistan', 'Saudia', 'Turkey', 'Palestine','Oman'], 'Pop':[250, 36,85,5,5]})
data

Country  Pop
0   Pakistan  250
1     Saudia   36
2     Turkey   85
3  Palestine    5
4       Oman    5

In [11]:
capitals = {'Oman':'Muscat', 'Pakistan':'Islamabad', "Saudia":'Riyad','Turkey':'Ankara', 'Palestine':'Gaza'}

In [14]:
data['Capitals'] = data.Country.map(capitals)

In [15]:
data

Country  Pop   Capitals
0   Pakistan  250  Islamabad
1     Saudia   36      Riyad
2     Turkey   85     Ankara
3  Palestine    5       Gaza
4       Oman    5     Muscat

In [17]:
import pandas as pd

df = pd.DataFrame([('carrot', 'red', 1), ('papaya', 'yellow', 0),('mango', 'yellow', 0), 
('apple', 'red', 0)], columns=['species', 'color', 'type'])
print("Dataframe before Mapping: ")
df

Dataframe before Mapping: 


species   color  type
0  carrot     red     1
1  papaya  yellow     0
2   mango  yellow     0
3   apple     red     0

In [18]:
mappings = {'carrot': 'veg','papaya': 'fruit'}

df['type_name'] = df['species'].map(mappings)


In [20]:
print("Dataframe after Mapping: ")
df

Dataframe after Mapping: 


species   color  type type_name
0  carrot     red     1       veg
1  papaya  yellow     0     fruit
2   mango  yellow     0       NaN
3   apple     red     0       NaN

In [21]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon','Pastrami', 'corned beef', 'Bacon','pastrami', 'honey ham', 'nova lox'],
'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [22]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [27]:
data.food = data.food.apply(lambda x:x.lower())

In [28]:
meat_to_animal = {'bacon': 'pig','pulled pork': 'pig','pastrami': 'cow','corned beef': 'cow','honey ham': 'pig','nova lox': 'salmon'
}

In [29]:
data['Meat_to_animal'] = data.food.map(meat_to_animal)
data

food  ounces Meat_to_animal
0        bacon     4.0            pig
1  pulled pork     3.0            pig
2        bacon    12.0            pig
3     pastrami     6.0            cow
4  corned beef     7.5            cow
5        bacon     8.0            pig
6     pastrami     3.0            cow
7    honey ham     5.0            pig
8     nova lox     6.0         salmon

# Replacing Values

In [30]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [31]:
data.apply(lambda x: 0 if x<=-999 else x)

0    1.0
1    0.0
2    2.0
3    0.0
4    0.0
5    3.0
dtype: float64

In [32]:
data.replace(-999,0)

0       1.0
1       0.0
2       2.0
3       0.0
4   -1000.0
5       3.0
dtype: float64

In [35]:
[1,2,3].apply(lambda x:x*2)

AttributeError: 'list' object has no attribute 'apply'

# Discretization and Binning

In [36]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [37]:
bins = [18, 25, 35, 60, 100]

In [46]:
cats = pd.cut(ages, bins, labels=['Bacha', 'Jawan', 'Bezar', 'Intizar'])

In [47]:
cats

['Bacha', 'Bacha', 'Bacha', 'Jawan', 'Bacha', ..., 'Jawan', 'Intizar', 'Bezar', 'Bezar', 'Jawan']
Length: 12
Categories (4, object): ['Bacha' < 'Jawan' < 'Bezar' < 'Intizar']

In [48]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [49]:
pd.value_counts(cats)

Bacha      5
Jawan      3
Bezar      3
Intizar    1
Name: count, dtype: int64

# Permutation and Random Sampling

In [50]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [51]:
sampler = np.random.permutation(5)
sampler

array([3, 1, 2, 0, 4])

In [52]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
1   4   5   6   7
2   8   9  10  11
0   0   1   2   3
4  16  17  18  19

In [53]:
df.sample(5)

0   1   2   3
4  16  17  18  19
2   8   9  10  11
0   0   1   2   3
1   4   5   6   7
3  12  13  14  15

In [61]:
data = pd.read_excel('SaleData.xlsx',index_col='S.No.')

In [62]:
data 

OrderDate   Region  Manager   SalesMan          Item  Units  \
S.No.                                                                
1     2019-08-07  Central  Hermann     Shelli   Video Games   42.0   
2     2019-08-24     West  Timothy    Stephen          Desk    3.0   
3     2019-09-10  Central  Timothy      David    Television    7.0   
4     2018-01-06     East   Martha  Alexander    Television   95.0   
5     2018-01-23  Central  Hermann     Shelli  Home Theater   50.0   
6     2018-02-09  Central  Hermann       Luis    Television   36.0   
7     2018-02-26  Central      NaN      David    Cell Phone   27.0   
8     2018-03-15     West  Timothy    Stephen    Television    NaN   
9     2018-04-01     East   Martha  Alexander  Home Theater   60.0   
10    2018-04-18      NaN   Martha     Steven    Television   75.0   
11    2018-05-05  Central  Hermann        NaN    Television   90.0   
12    2018-05-22     West  Douglas    Michael    Television   32.0   
13    2018-06-08     East   Martha  Alexander  Home Theater   60.0   
14    2018-06-25  Central  Hermann      Sigal    Television   90.0   
15    2018-07-12     East   Martha      Diana  Home Theater   29.0   
16    2018-07-29      NaN  Douglas      Karen  Home Theater   81.0   
17    2018-08-15     East   Martha  Alexander           NaN   35.0   
18    2018-09-01  Central  Douglas       John          Desk    2.0   
19    2018-09-18     East   Martha  Alexander   Video Games   16.0   
20    2018-10-05  Central  Hermann      Sigal  Home Theater   28.0   
21    2018-10-22     East   Martha  Alexander    Cell Phone   64.0   
22    2018-11-08     East  Douglas      Karen    Cell Phone   15.0   
23    2018-11-25  Central  Hermann     Shelli   Video Games   96.0   
24    2018-12-12  Central  Douglas       John    Television   67.0   
25    2018-12-29     East  Douglas      Karen           NaN   74.0   
26    2019-01-15  Central  Timothy      David  Home Theater   46.0   
27    2019-02-01  Central  Douglas       John  Home Theater   87.0   
28    2019-02-18     East   Martha  Alexander  Home Theater    4.0   
29    2019-03-07     West  Timothy    Stephen  Home Theater    7.0   
30    2019-03-24  Central  Hermann       Luis   Video Games   50.0   
31    2019-04-10  Central   Martha     Steven    Television    NaN   
32    2019-04-27     East   Martha      Diana    Cell Phone   96.0   
33    2019-05-14  Central  Timothy      David    Television   53.0   
34    2019-05-31  Central  Timothy      David  Home Theater   80.0   
35    2019-06-17  Central  Hermann     Shelli          Desk    5.0   
36    2019-07-04     East   Martha  Alexander   Video Games    NaN   
37    2019-07-21  Central  Hermann      Sigal   Video Games   55.0   
38    2019-08-07  Central  Hermann        NaN   Video Games   42.0   
39    2019-08-24     West  Timothy    Stephen          Desk    3.0   
40    2019-09-10  Central  Timothy      David    Television    7.0   
41    2019-09-27     West  Timothy    Stephen    Cell Phone   76.0   
42    2019-10-14     West  Douglas    Michael  Home Theater   57.0   
43    2019-10-31  Central   Martha     Steven    Television   14.0   
44    2019-11-17  Central  Hermann       Luis  Home Theater   11.0   
45    2019-12-04  Central  Hermann       Luis  Home Theater   94.0   
46    2019-12-21  Central   Martha     Steven  Home Theater   28.0   
47    2019-04-27     East   Martha      Diana    Cell Phone   96.0   
48    2019-02-01  Central  Douglas       John  Home Theater   87.0   
49    2019-03-24  Central  Hermann       Luis   Video Games   50.0   
50    2019-04-10  Central   Martha     Steven    Television   66.0   
51    2019-04-27     East   Martha      Diana    Cell Phone   96.0   
52    2019-05-14  Central  Timothy      David    Television   53.0   

       Unit_price  Sale_amt  
S.No.                        
1            58.5    2457.0  
2           125.0     375.0  
3          1198.0    8386.0  
4          1198.0  113810.0  
5           500.0   25000.0  
6          1198.

In [64]:
data.Region.value_counts()

Region
Central    29
East       14
West        7
Name: count, dtype: int64

In [65]:
pd.get_dummies(data.Region)

Central   East   West
S.No.                       
1         True  False  False
2        False  False   True
3         True  False  False
4        False   True  False
5         True  False  False
6         True  False  False
7         True  False  False
8        False  False   True
9        False   True  False
10       False  False  False
11        True  False  False
12       False  False   True
13       False   True  False
14        True  False  False
15       False   True  False
16       False  False  False
17       False   True  False
18        True  False  False
19       False   True  False
20        True  False  False
21       False   True  False
22       False   True  False
23        True  False  False
24        True  False  False
25       False   True  False
26        True  False  False
27        True  False  False
28       False   True  False
29       False  False   True
30        True  False  False
31        True  False  False
32       False   True  False
33        True  False  False
34        True  False  False
35        True  False  False
36       False   True  False
37        True  False  False
38        True  False  False
39       False  False   True
40        True  False  False
41       False  False   True
42       False  False   True
43        True  False  False
44        True  False  False
45        True  False  False
46        True  False  False
47       False   True  False
48        True  False  False
49        True  False  False
50        True  False  False
51       False   True  False
52        True  False  False

In [68]:
data.SalesMan.value_counts()

SalesMan
Alexander    8
David        7
Stephen      5
Luis         5
Steven       5
Shelli       4
Diana        4
John         4
Sigal        3
Karen        3
Michael      2
Name: count, dtype: int64

In [66]:
pd.get_dummies(data)

OrderDate  Units  Unit_price  Sale_amt  Region_Central  Region_East  \
S.No.                                                                        
1     2019-08-07   42.0        58.5    2457.0            True        False   
2     2019-08-24    3.0       125.0     375.0           False        False   
3     2019-09-10    7.0      1198.0    8386.0            True        False   
4     2018-01-06   95.0      1198.0  113810.0           False         True   
5     2018-01-23   50.0       500.0   25000.0            True        False   
6     2018-02-09   36.0      1198.0   43128.0            True        False   
7     2018-02-26   27.0       225.0    6075.0            True        False   
8     2018-03-15    NaN      1198.0       0.0           False        False   
9     2018-04-01   60.0       500.0   30000.0           False         True   
10    2018-04-18   75.0      1198.0   89850.0           False        False   
11    2018-05-05   90.0      1198.0  107820.0            True        False   
12    2018-05-22   32.0      1198.0   38336.0           False        False   
13    2018-06-08   60.0       500.0   30000.0           False         True   
14    2018-06-25   90.0      1198.0  107820.0            True        False   
15    2018-07-12   29.0       500.0   14500.0           False         True   
16    2018-07-29   81.0       500.0   40500.0           False        False   
17    2018-08-15   35.0      1198.0   41930.0           False         True   
18    2018-09-01    2.0       125.0     250.0            True        False   
19    2018-09-18   16.0        58.5     936.0           False         True   
20    2018-10-05   28.0       500.0   14000.0            True        False   
21    2018-10-22   64.0       225.0   14400.0           False         True   
22    2018-11-08   15.0       225.0    3375.0           False         True   
23    2018-11-25   96.0        58.5    5616.0            True        False   
24    2018-12-12   67.0      1198.0   80266.0            True        False   
25    2018-12-29   74.0        58.5    4329.0           False         True   
26    2019-01-15   46.0       500.0   23000.0            True        False   
27    2019-02-01   87.0       500.0   43500.0            True        False   
28    2019-02-18    4.0       500.0    2000.0           False         True   
29    2019-03-07    7.0       500.0    3500.0           False        False   
30    2019-03-24   50.0        58.5    2925.0            True        False   
31    2019-04-10    NaN      1198.0       0.0            True        False   
32    2019-04-27   96.0       225.0   21600.0           False         True   
33    2019-05-14   53.0      1198.0   63494.0            True        False   
34    2019-05-31   80.0       500.0   40000.0            True        False   
35    2019-06-17    5.0       125.0     625.0            True        False   
36    2019-07-04    NaN        58.5       0.0           False         True   
37    2019-07-21   55.0        58.5    3217.5            True        False   
38    2019-08-07   42.0        58.5    2457.0            True        False   
39    2019-08-24    3.0       125.0     375.0           False        False   
40    2019-09-10    7.0      1198.0    8386.0            True        False   
41    2019-09-27   76.0       225.0   17100.0           False        False   
42    2019-10-14   57.0       500.0   28500.0           False        False   
43    2019-10-31   14.0      1198.0   16772.0            True        False   
44    2019-11-17   11.0       500.0    5500.0            True        False   
45    2019-12-04   94.0       500.0   47000.0            True        False   
46    2019-12-21   28.0       500.0   14000.0            True        False   
47    2019-04-27   96.0       225.0   21600.0           False         True   
48    2019-02-01   87.0       500.0   43500.0            True        False   
49    2019-03-24   50.0        58.5    2925.0            True        False   
50    2019-04-10   66.0      

In [86]:
import sklearn

In [70]:
from sklearn.preprocessing import OneHotEncoder

In [73]:
ohe = OneHotEncoder()

In [85]:
ohe.fit_transform(data[['Region']]).toarray()

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],


In [82]:
ohe.categories_

[array(['Central', 'East', 'West', nan], dtype=object)]

In [88]:
colors = pd.DataFrame({'colors':['Red', 'Green', 'Blue', 'Yellow', 'Orange', 'Black']})

In [89]:
colors

colors
0     Red
1   Green
2    Blue
3  Yellow
4  Orange
5   Black

In [90]:
pd.get_dummies(colors)

colors_Black  colors_Blue  colors_Green  colors_Orange  colors_Red  \
0         False        False         False          False        True   
1         False        False          True          False       False   
2         False         True         False          False       False   
3         False        False         False          False       False   
4         False        False         False           True       False   
5          True        False         False          False       False   

   colors_Yellow  
0          False  
1          False  
2          False  
3           True  
4          False  
5          False

In [91]:
ohe.fit_transform(colors).toarray()

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.]])