# Python for Data Analytics

 - Numpy 
 - Pandas 
 - Matplotlib /Seaborn
 - Power Bi
 - Statistics
 - Predictive Analytics (ML )

# Numpy

 - Numerical Python: 
                    - its an array written in C
 
                    - Fast 
                     
                    -  Vectorised Operation    

### Array Creation
       - python list
       - array()
       - arange()
       

In [ ]:
# !pip install numpy

In [1]:
import numpy as np

In [14]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [15]:
type(arr)

numpy.ndarray

In [16]:
# array size
arr.size

10

In [17]:
# array shape
arr.shape

(10,)

In [18]:
arr.ndim

1

In [19]:
arr[4]

5

In [20]:
arr[3:7]

array([4, 5, 6, 7])

In [21]:
arr[9:3:-1]

array([10,  9,  8,  7,  6,  5])

# 2D-aRRAY

In [31]:
arr2d = np.array([
                   [1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [11,22,33,44],
                   [11,22,33,44]
                 ])

In [32]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [11, 22, 33, 44],
       [11, 22, 33, 44]])

In [33]:
arr2d.size

20

In [34]:
arr2d.shape

(5, 4)

In [35]:
arr2d.ndim

2

In [36]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [11, 22, 33, 44],
       [11, 22, 33, 44]])

In [38]:
arr2d[1][2]

7

In [39]:
arr2d[1][2]

7

In [40]:
arr2d[1, 2]

7

In [41]:
arr2d[2,2]

11

# Indexing and Slicing

In [42]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [11, 22, 33, 44],
       [11, 22, 33, 44]])

In [43]:
arr2d = np.arange(64).reshape(8,8)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [45]:
# indexing
arr2d[ 1:9,3:6]

array([[11, 12, 13],
       [19, 20, 21],
       [27, 28, 29],
       [35, 36, 37],
       [43, 44, 45],
       [51, 52, 53],
       [59, 60, 61]])

In [29]:
arr2d[2][0]

16

In [ ]:
arr2d[3,3]

In [ ]:
#[r,c]>>> [startrow:endrow   , startcol:endcol]
arr2d[]

In [ ]:
arr2d

In [ ]:
arr2d[1:3,1:3]

In [ ]:
arr2d[2:3,1:3]

In [ ]:
arr2d[:,3:]

In [ ]:
arr2d[3:6,2:6]

In [ ]:
arr2d[1:,4:6]

In [ ]:
arr2d[:,1:7]

In [ ]:
arr2d[4:5,3:5]

In [46]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [48]:
arr2d[2][6] = 2200

In [49]:
arr2d

array([[   0,    1,    2,    3,    4,    5,    6,    7],
       [   8,    9,   10,   11,   12,   13,   14,   15],
       [  16,   17,   18,   19,   20,   21, 2200,   23],
       [  24,   25,   26,   27,   28,   29,   30,   31],
       [  32,   33,   34,   35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44,   45,   46,   47],
       [  48,   49,   50,   51,   52,   53,   54,   55],
       [  56,   57,   58,   59,   60,   61,   62,   63]])

In [ ]:
a=arr2d[2,4]

In [ ]:
type(a)

# array 3d

In [ ]:
arr3d = np.arange(24).reshape(2,4,3) # (depth, row, col)
arr3d

In [ ]:
arr3d.ndim

In [ ]:
arr3d[1,1,1]

In [ ]:
arr3d[1,2,2]

# Vectorized Operation:

In [ ]:
arr

In [ ]:
lst=[]
for a in arr:
    lst.append(a*10)

In [ ]:
lst

In [ ]:
arr

In [ ]:
arr*2

In [ ]:
arr2d

In [ ]:
arr2d/10