In [3]:
import numpy as np

In [4]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr1d[4]

4

In [6]:
arr1d[2:6]

array([2, 3, 4, 5])

In [7]:
arr1d.shape

(10,)

# 2D-Array Numpy 

In [8]:
arr2d = np.arange(16).reshape(4,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
arr2d = np.arange(64).reshape(8,8)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

# Indexing & Slicing

In [10]:
arr2d[3,4]

28

In [11]:
arr2d[6,6]

54

In [12]:
# array_name[row,col]>>>> array_name[s_row:e_row,s_col:e_col]

arr2d[6:7,6:7]

array([[54]])

In [13]:
arr2d[3:6,2:6]

array([[26, 27, 28, 29],
       [34, 35, 36, 37],
       [42, 43, 44, 45]])

In [14]:
arr2d[0:6,2:6]

array([[ 2,  3,  4,  5],
       [10, 11, 12, 13],
       [18, 19, 20, 21],
       [26, 27, 28, 29],
       [34, 35, 36, 37],
       [42, 43, 44, 45]])

In [15]:
arr2d[:,6:]

array([[ 6,  7],
       [14, 15],
       [22, 23],
       [30, 31],
       [38, 39],
       [46, 47],
       [54, 55],
       [62, 63]])

In [16]:
arr2d[:,1]

array([ 1,  9, 17, 25, 33, 41, 49, 57])

In [17]:
arr2d[:,1:2]

array([[ 1],
       [ 9],
       [17],
       [25],
       [33],
       [41],
       [49],
       [57]])

In [18]:
arr2d[:,1:]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 9, 10, 11, 12, 13, 14, 15],
       [17, 18, 19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29, 30, 31],
       [33, 34, 35, 36, 37, 38, 39],
       [41, 42, 43, 44, 45, 46, 47],
       [49, 50, 51, 52, 53, 54, 55],
       [57, 58, 59, 60, 61, 62, 63]])

In [19]:
arr2d[:,::-1]

array([[ 7,  6,  5,  4,  3,  2,  1,  0],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [23, 22, 21, 20, 19, 18, 17, 16],
       [31, 30, 29, 28, 27, 26, 25, 24],
       [39, 38, 37, 36, 35, 34, 33, 32],
       [47, 46, 45, 44, 43, 42, 41, 40],
       [55, 54, 53, 52, 51, 50, 49, 48],
       [63, 62, 61, 60, 59, 58, 57, 56]])

In [20]:
arr2d[3:4, 1:]

array([[25, 26, 27, 28, 29, 30, 31]])

In [21]:
arr3d = np.arange(50).reshape(2,5,5)# depth, row, column
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [22]:
arr3d[1,1,3]

33

In [23]:
arr3d[1:2,3:4,1:3]

array([[[41, 42]]])

In [24]:
arr2d_1= np.arange(1,17).reshape(4,4)
arr2d_2= np.arange(17,33).reshape(4,4)

In [25]:
arr2d_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
arr2d_1.shape
arr2d_2.shape

(4, 4)

In [27]:
arr2d_2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [28]:
a = np.hstack([arr2d_1,arr2d_2])

In [29]:
a

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [30]:
a = np.vstack([arr2d_1,arr2d_2])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [31]:
arr2d = np.arange(30).reshape(5,6)
arr2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [32]:
new2d = np.arange(36).reshape(6,6)
new2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [33]:
np.vstack([arr2d,new2d])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [34]:
np.hstack([arr2d,new2d])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 6

In [ ]:
arr2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
np.hsplit(arr2d,2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29]])]

In [ ]:
np.vsplit(arr2d,2)

ValueError: array split does not result in an equal division

In [39]:
a = np.random.randint(50, size=(5, 3))
a

array([[ 6,  6, 21],
       [21, 30, 25],
       [10, 47,  7],
       [41, 38, 23],
       [24, 37, 34]])

In [41]:
a>45

array([[False, False, False],
       [False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [44]:
# masking or condition based data selection
a[a>5]

array([ 6,  6, 21, 21, 30, 25, 10, 47,  7, 41, 38, 23, 24, 37, 34])

In [45]:
a[(a>=5) & (a<=10)]

array([ 6,  6, 10,  7])

In [48]:
import pandas as pd

data = pd.read_csv("./ChurnData.csv")

ModuleNotFoundError: No module named 'pandas'

In [49]:
data

NameError: name 'data' is not defined

In [ ]:
data[data.Model=='Agfa ePhoto 1280']

Model  Release date  Max resolution  ...  Weight (inc. batteries)  Dimensions  Price
0  Agfa ePhoto 1280          1997          1024.0  ...                    420.0        95.0  179.0

[1 rows x 13 columns]

In [ ]:
[ {a:a**2} for a in range(10)]

[{0: 0},
 {1: 1},
 {2: 4},
 {3: 9},
 {4: 16},
 {5: 25},
 {6: 36},
 {7: 49},
 {8: 64},
 {9: 81}]

In [ ]:
[{a: a.upper()} for a in "pakistan"]

[{'p': 'P'},
 {'a': 'A'},
 {'k': 'K'},
 {'i': 'I'},
 {'s': 'S'},
 {'t': 'T'},
 {'a': 'A'},
 {'n': 'N'}]