# Concatenating Arrays

In [1]:
import numpy as np
arr2d_a = np.arange(25).reshape(5,5)
arr2d_b = np.arange(25,50).reshape(5,5)

In [2]:
arr2d_a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [3]:
arr2d_b

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [4]:
merged_array = np.concatenate([arr2d_a,arr2d_b])

In [5]:
merged_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [6]:
merged_array = np.concatenate([arr2d_a,arr2d_b],axis=1)

In [7]:
merged_array

array([[ 0,  1,  2,  3,  4, 25, 26, 27, 28, 29],
       [ 5,  6,  7,  8,  9, 30, 31, 32, 33, 34],
       [10, 11, 12, 13, 14, 35, 36, 37, 38, 39],
       [15, 16, 17, 18, 19, 40, 41, 42, 43, 44],
       [20, 21, 22, 23, 24, 45, 46, 47, 48, 49]])

In [8]:
arr2d_a.shape

(5, 5)

In [9]:
arr2d_b.shape

(5, 5)

In [11]:
arr2d_a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
np.split(arr2d_a,2,axis=0)

ValueError: array split does not result in an equal division

In [16]:
arr2d_c = np.arange(36).reshape(6,6)

In [17]:
arr2d_c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [26]:
newArray= np.split(arr2d_c,2,axis=0)
newArray

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [24]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [25]:
B

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [28]:
teri, meri = [[1,2,3],[3,4,5]]

In [29]:
teri

[1, 2, 3]

In [30]:
meri

[3, 4, 5]

In [31]:
choti_wali_teri, bari_wali_meri= np.split(arr2d_c,2,axis=1)

In [32]:
choti_wali_teri

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20],
       [24, 25, 26],
       [30, 31, 32]])

In [33]:
bari_wali_meri

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])

In [34]:
a,b,c,d,e,f = np.split(arr2d_c,6,axis=1)

In [35]:
a

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [36]:
b

array([[ 1],
       [ 7],
       [13],
       [19],
       [25],
       [31]])

In [37]:
c

array([[ 2],
       [ 8],
       [14],
       [20],
       [26],
       [32]])

In [38]:
 zero = np.zeros(10)

In [39]:
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
zero_2d = np.zeros((5,5))
zero_2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
ones_2d = np.ones((5,5))
ones_2d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
ones_2d = np.ones((10,10))*10
ones_2d

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [51]:
np.full((5,5), fill_value=10,)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [52]:
np.empty((4,4))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.69118787e-306],
       [2.67014296e-307, 7.56603203e-307, 7.56587585e-307,
        1.37961302e-306],
       [1.05699242e-307, 3.11523242e-307, 2.22523140e-306,
        1.02360867e-306],
       [1.86921958e-306, 6.89804133e-307, 1.11261162e-306,
        8.34443015e-308]])

In [57]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
arr = np.arange(12).reshape(4,3)
arr.dtype

dtype('int32')

In [64]:
arr[2,2] = 4.5

In [65]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  4],
       [ 9, 10, 11]])

In [78]:
a = np.array([1,2,3,4,5,6])

In [79]:
np.ones_like(a)

array([1, 1, 1, 1, 1, 1])

In [80]:
arr2d = np.random.randint(1,10,(5,5))
arr2d

array([[9, 9, 8, 1, 3],
       [3, 1, 4, 7, 6],
       [8, 3, 3, 7, 2],
       [3, 4, 9, 2, 7],
       [3, 7, 6, 7, 8]])

In [81]:
arr2d>5

array([[ True,  True,  True, False, False],
       [False, False, False,  True,  True],
       [ True, False, False,  True, False],
       [False, False,  True, False,  True],
       [False,  True,  True,  True,  True]])

In [82]:
arr2d[arr2d>5]

array([9, 9, 8, 7, 6, 8, 7, 9, 7, 7, 6, 7, 8])

In [84]:
arr2d[(arr2d>5) & (arr2d<8)]

array([7, 6, 7, 7, 7, 6, 7])

In [85]:
arr2d[(arr2d>5) & (arr2d%2==0)]

array([8, 6, 8, 6, 8])

In [86]:
arr2d[(arr2d>5) | (arr2d%2==0)]

array([9, 9, 8, 4, 7, 6, 8, 7, 2, 4, 9, 2, 7, 7, 6, 7, 8])

In [89]:
np.where(arr2d>5,0,arr2d)

array([[0, 0, 0, 1, 3],
       [3, 1, 4, 0, 0],
       [0, 3, 3, 0, 2],
       [3, 4, 0, 2, 0],
       [3, 0, 0, 0, 0]])

# Pandas 

### Pandas Data Structure
    ## - Series 
    ## - DataFrame

# Series

In [93]:
s1 = pd.Series([10,12,14,20,22,24])
s1

0    10
1    12
2    14
3    20
4    22
5    24
dtype: int64

In [95]:
print(type(s1))

<class 'pandas.core.series.Series'>


In [96]:
s1.size

6

In [97]:
s1.shape

(6,)

In [98]:
s1.index

RangeIndex(start=0, stop=6, step=1)

In [99]:
s1.values

array([10, 12, 14, 20, 22, 24], dtype=int64)

In [100]:
s1 = pd.Series([10,12,14,20,22,24], index=["Anday", "Burger", "Apples","Mangoes", "Alo", "Tomato"])
s1

Anday      10
Burger     12
Apples     14
Mangoes    20
Alo        22
Tomato     24
dtype: int64

In [101]:
s1['Anday']

10

In [103]:
s1['Mangoes']

20

In [104]:
s1[4]

22

In [106]:
s1[2:5]

Apples     14
Mangoes    20
Alo        22
dtype: int64

In [107]:
s1["Apples":"Tomato"]

Apples     14
Mangoes    20
Alo        22
Tomato     24
dtype: int64